; Inno Setup Script for VoiceFlow Dictation
; Auto-generated by PyInstaller build process

[Setup]
; Basic info
AppName=VoiceFlow Dictation
AppVersion=1.0
AppPublisher=XgenF1
AppUrl=https://github.com/openai/whisper
AppSupportUrl=https://github.com/openai/whisper
AppUpdatesUrl=https://github.com/openai/whisper
; Request execution level for registry access (autostart)
RequestExecutionLevel=user

; Default output directory
DefaultDirName={app}\VoiceFlow Dictation
; Default group name in Start Menu
DefaultGroupName=VoiceFlow Dictation
; Output base filename
OutputBaseFilename=VoiceFlow_Dictation_Installer

; Default language
Languages=english

; Installable languages
[Languages]
Name: english; MessagesFile: langs\english.isl

; Icons
[Icons]
Name: "{group}\VoiceFlow Dictation"; Filename: "{app}\dictation.exe"
Name: "{commondesktop}\VoiceFlow Dictation"; Filename: "{app}\dictation.exe"
Name: "{group}\Uninstall VoiceFlow Dictation"; Filename: "{uninstallexe}"

; Files
[Files]
; Install the PyInstaller executable
Source: "dist\dictation.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\.env"; DestDir: "{app}"; Flags: ignoreversion
; Include the app icon
Source: "assets\app.ico"; DestDir: "{app}"; Flags: iconfile

; Registry: create uninstall entry
UninstallCategory=Utilities

; User strings
[Strings]
AppName = "VoiceFlow Dictation"
Publisher = "XgenF1"

; Tasks
[Tasks]
Name: "create_desktop_shortcut"; Description: "Create a desktop shortcut"; Flags: checked
Name: "autostart"; Description: "Start VoiceFlow Dictation when Windows starts"; Flags: checked

; Registry for autostart
[Registry]
; Add to Windows startup
Root: "HKLM"; Key: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueName: "VoiceFlowDictation"; ValueType: string; ValueData: "{app}\dictation.exe"; Checked: "autostart"

; Uninstaller
[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Tasks]
Name: "desktop"; Description: "Create a desktop shortcut"; Flags: checked
Name: "autostart"; Description: "Start VoiceFlow Dictation when Windows starts"; Flags: radio

[Registry]
Type: write; Root: "HKLM"; Key: "Software\Microsoft\Windows\CurrentVersion\Uninstall\VoiceFlow Dictation"; ValueName: "DisplayName"; ValueType: string; ValueData: "VoiceFlow Dictation"
Type: write; Root: "HKLM"; Key: "Software\Microsoft\Windows\CurrentVersion\Uninstall\VoiceFlow Dictation"; ValueName: "DisplayVersion"; ValueType: string; ValueData: "1.0"
Type: write; Root: "HKLM"; Key: "Software\Microsoft\Windows\CurrentVersion\Uninstall\VoiceFlow Dictation"; ValueName: "UninstallString"; ValueType: string; ValueData: '"{uninstallexe}"'
Type: write; Root: "HKLM"; Key: "Software\Microsoft\Windows\CurrentVersion\Uninstall\VoiceFlow Dictation"; ValueName: "DisplayIcon"; ValueType: string; ValueData: "{app}\dictation.exe"

; Custom task for autostart
[Run]
Type: inline; AppName: "VoiceFlow Dictation"; Filename: "{app}\dictation.exe"; Parameters: "-startup"; StatusMsg: "Setting up autostart..."; Flags: skipifsilent

; Custom task for desktop shortcut (handled by Icons section)

; Post-install
[Run]
Type: inline; AppName: "VoiceFlow Dictation"; Filename: "{app}\dictation.exe"; Parameters: "--firstrun"; StatusMsg: "Initializing VoiceFlow Dictation..."; Flags: skipifsilent

; ------------------------------------------------
; --- Custom Pages and Event Handlers ----------
; ------------------------------------------------

[Code]

; ------------------------------------------------
; --- Helper functions ----------
; ------------------------------------------------

function GetAppPath: string;
begin
  Result := ExpandConstant('{app}');
end;

; ------------------------------------------------
; --- OnInit ----------
; ------------------------------------------------

procedure OnInit();
begin
  ; Ensure .env file exists next to exe for the app to read
  if not FileExists(ExpandConstant('{app}\.env')) then
  begin
    ; Copy default .env template if it doesn't exist
    if not FileExists(ExpandConstant('{src}\.env.example')) then
      MsgBox MB_OK, 'VoiceFlow Dictation', 'Could not find configuration template. Please run the application once to set up your Groq API key.';
  end;
end;

; ------------------------------------------------
; --- Custom Messages ----------
; ------------------------------------------------

[Messages]
RunButton = '&Run'
SkipButton = 'Skip'